name: Deploy to DigitalOcean

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        
        sudo apt-get install -y rsync openssh-client

    - name: Add SSH key to agent
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Scan and add SSH host to known_hosts
      run: |
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy code
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ eustaciasukarto@${{ secrets.SSH_HOST }}:/var/www/esukartocse135.com/public_html
