name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync

    - name: Deploy code
      run: |
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        rsync -avz --delete -e "ssh -i <(echo '${{ secrets.SSH_KEY }}')" ./ deployer@${{ secrets.SSH_HOST }}:/var/www/html