name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ssh rsync

    - name: Deploy
      run: |
        ssh-keyscan 146.190.65.27 >> ~/.ssh/known_hosts
        rsync -avz --delete ./ eustaciasukarto@146.190.65.27:/var/www/html/